In [1]:
import numpy as np

In [2]:
# task 1
arr1d = np.arange(1, 11)
print("1D Array:", arr1d)
arr2d = np.random.randint(1, 10, size=(3, 3))
print("2D Array:\n", arr2d)

1D Array: [ 1  2  3  4  5  6  7  8  9 10]
2D Array:
 [[7 6 6]
 [6 8 4]
 [9 4 1]]


In [3]:
# task 2
print("Sum:", arr1d.sum())
print("Mean:", arr1d.mean())
print("Max:", arr1d.max())

arr_multiplied = arr1d * 2
print("Multiplied by 2:", arr_multiplied)

arr_replaced = arr1d.copy()
arr_replaced[arr_replaced > 5] = 0
print("Replaced >5 with 0:", arr_replaced)

Sum: 55
Mean: 5.5
Max: 10
Multiplied by 2: [ 2  4  6  8 10 12 14 16 18 20]
Replaced >5 with 0: [1 2 3 4 5 0 0 0 0 0]
